# Generated by Django 5.0.1 on 2024-01-16 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_1_app', '0002_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='many_user',
            field=models.ManyToManyField(related_name='many_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
