# Generated by Django 5.0.1 on 2024-01-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_1_app', '0003_product_many_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='many_user',
        ),
    ]
