from .user import User
from .products import Product
from .directors import Director
from .films import Film
from .phones_book import Phones
from .news import News
from .like import Like
from .news_comment import CommentNews
from .goods import Goods